### PR TITLE
Providing a source-filename and some cleanup

### PR DESCRIPTION
**Pull request by DuimTechniek**
I've provided the "put" operation with the functionality of giving it a source file instead of filedata. That way we don't have to write filedata to a temp file if the file already exists.

Also did a bit of cleaning up the code.

### CODE REVIEW

**Comment by travisghansen** [comment]
Wow awesome! I won't have time to review for a couple days but I'll provide feedback as quickly as I can.

Thanks!

**Comment by travisghansen** [comment]
What linting options did you use on this? The previous formatting is the defaults used by VS Code so it'll my IDE will completely reverse all those changes as soon as I save the file..

**Comment by DuimTechniek** [comment]
Ah that's my bad, I use a custom one. I used the standard one and pushed it

**Comment by travisghansen** [comment]
Something must still be off between our eslint configs..mine forces double quote and is ending statements with semicolon (not saying it's standard or right, just that we're still off).

**Comment by DuimTechniek** [comment]
Also fixed and pushed

**Comment by travisghansen** [comment]
Looks like we still have a couple minor differences. Maybe I can figure out how to produce the defaults my setup is using and then commit it local to the project...

Now that most of the noise is out of the diff though I have a better idea where you're headed with it..I'll give it a more thorough review but generally appears ok.

**Comment by travisghansen** [comment]
Going to look at this today FYI..

**Comment by travisghansen** [comment]
I've published to npm as `0.3.0`.

**Comment by travisghansen** [comment]
Thanks for the contributions!

**Pull request merged**
